export const quizArray = [
  {
    id: "codingMedium1",
    question: "Which of the following is a programming language?",
    answers: ["HTML", "CSS", "Python", "Markdown"],
    rightAnswer: 2,
    category: "Coding",
    difficulty: "medium",
  },
  {
    id: "codingMedium2",
    question: "What is a for-loop used for?",
    answers: ["Store data", "Repeat code", "Sort files", "Stop execution"],
    rightAnswer: 1,
    category: "Coding",
    difficulty: "medium",
  },
  {
    id: "codingMedium3",
    question: "Which CSS selector has the highest specificity?",
    answers: [".nav-item", "div p", "button:hover", "#header"],
    rightAnswer: 3,
    category: "Coding",
    difficulty: "medium",
  },
  {
    id: "codingMedium4",
    question: "What does 'HTML' stand for?",
    answers: [
      "HighText Modern Language",
      "Hyper Transfer Machine Language",
      "HyperText Markup Language",
      "Hyperlink Text Management Language",
    ],
    rightAnswer: 2,
    category: "Coding",
    difficulty: "medium",
  },
  {
    id: "codingMedium5",
    question: "What type of data type is 'true' in most languages?",
    answers: ["String", "Character", "Boolean", "Integer"],
    rightAnswer: 2,
    category: "Coding",
    difficulty: "medium",
  },
  {
    id: "gamingMedium1",
    question: "Which console was created by Sony?",
    answers: ["PlayStation", "Nintendo Switch", "Xbox", "Sega Genesis"],
    rightAnswer: 0,
    category: "Gaming",
    difficulty: "medium",
  },
  {
    id: "gamingMedium2",
    question: "In which game do you collect resources and build with blocks?",
    answers: ["Fortnite", "Terraria", "Roblox", "Minecraft"],
    rightAnswer: 3,
    category: "Gaming",
    difficulty: "medium",
  },
  {
    id: "gamingMedium3",
    question: "What is the name of the main character in the Halo series?",
    answers: ["Cortana", "Sergeant Johnson", "Master Chief", "Arbiter"],
    rightAnswer: 2,
    category: "Gaming",
    difficulty: "medium",
  },
  {
    id: "gamingMedium4",
    question: "What is the name of the company that owns Steam?",
    answers: ["EA", "Ubisoft", "Epic Games", "Valve"],
    rightAnswer: 3,
    category: "Gaming",
    difficulty: "medium",
  },
  {
    id: "gamingMedium5",
    question: "Which character is known for the quote 'Do a barrel roll!'?",
    answers: ["Solid Snake", "Fox McCloud", "Mario", "Link"],
    rightAnswer: 1,
    category: "Gaming",
    difficulty: "medium",
  },
  {
    id: "gamingMedium6",
    question:
      "What is the name of the blue hedgehog that runs fast in Sega's game series?",
    answers: ["Sonic", "Knuckles", "Crash", "Shadow"],
    rightAnswer: 0,
    category: "Gaming",
    difficulty: "medium",
  },
  {
    id: "gamingMedium7",
    question: "In which game do you encounter the character GLaDOS?",
    answers: ["Mass Effect", "Portal", "Half-Life 2", "Bioshock"],
    rightAnswer: 1,
    category: "Gaming",
    difficulty: "medium",
  },
  {
    id: "gamingMedium8",
    question: "Which character is the princess in the Super Mario series?",
    answers: ["Peach", "Zelda", "Rosalina", "Daisy"],
    rightAnswer: 0,
    category: "Gaming",
    difficulty: "medium",
  },
  {
    id: "gamingMedium9",
    question: "Which hero wears a green tunic and often uses the Master Sword?",
    answers: ["Ganondorf", "Zelda", "Epona", "Link"],
    rightAnswer: 3,
    category: "Gaming",
    difficulty: "medium",
  },
];
